# Generated by Django 2.1.7 on 2019-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_spend', models.CharField(max_length=50)),
                ('money', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('isPri', models.BooleanField()),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
